CRITICAL - 2023-01-24 01:30:23 --> cURL error 35: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api-ap1.pusher.com:443  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api-ap1.pusher.com/apps/1541690/events?auth_key=81fed0e008d5c25a0657&auth_timestamp=1674545423&auth_version=1.0&body_md5=edc6657a206fd78964d50cf2232316a3&auth_signature=7eca59410651e2a1c1df0eb5f00e397105c6be9c0f4be8a01dbadaf7252a9fb2
in VENDORPATH\pusher\pusher-php-server\src\Pusher.php on line 782.
 1 VENDORPATH\pusher\pusher-php-server\src\Pusher.php(440): Pusher\Pusher->post('/apps/1541690/events', '{"name":"my-event","data":"{\\"message\\":\\"Ada Artikel Yang Harus di Verifikasi\\"}","channel":"my-channel"}')
 2 APPPATH\Controllers\Article.php(91): Pusher\Pusher->trigger('my-channel', 'my-event', [...])
 3 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Article->save()
 4 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Article))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-01-24 01:42:31 --> syntax error, unexpected 'else' (T_ELSE)
in APPPATH\Views\admin\article.php on line 55.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 2 SYSTEMPATH\Common.php(1177): CodeIgniter\View\View->render('admin/article', [], true)
 3 APPPATH\Controllers\Article.php(30): view('admin/article', [...])
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Article->index()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Article))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-01-24 01:42:53 --> syntax error, unexpected 'else' (T_ELSE)
in APPPATH\Views\admin\article.php on line 55.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 2 SYSTEMPATH\Common.php(1177): CodeIgniter\View\View->render('admin/article', [], true)
 3 APPPATH\Controllers\Article.php(30): view('admin/article', [...])
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Article->index()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Article))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-01-24 01:43:43 --> syntax error, unexpected '{', expecting '('
in APPPATH\Views\admin\article.php on line 55.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 2 SYSTEMPATH\Common.php(1177): CodeIgniter\View\View->render('admin/article', [], true)
 3 APPPATH\Controllers\Article.php(30): view('admin/article', [...])
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Article->index()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Article))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-01-24 01:43:44 --> syntax error, unexpected '{', expecting '('
in APPPATH\Views\admin\article.php on line 55.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 2 SYSTEMPATH\Common.php(1177): CodeIgniter\View\View->render('admin/article', [], true)
 3 APPPATH\Controllers\Article.php(30): view('admin/article', [...])
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Article->index()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Article))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-01-24 01:43:44 --> syntax error, unexpected '{', expecting '('
in APPPATH\Views\admin\article.php on line 55.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 2 SYSTEMPATH\Common.php(1177): CodeIgniter\View\View->render('admin/article', [], true)
 3 APPPATH\Controllers\Article.php(30): view('admin/article', [...])
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Article->index()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Article))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-01-24 01:45:56 --> syntax error, unexpected 'endforeach' (T_ENDFOREACH)
in APPPATH\Views\admin\article.php on line 122.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 2 SYSTEMPATH\Common.php(1177): CodeIgniter\View\View->render('admin/article', [], true)
 3 APPPATH\Controllers\Article.php(30): view('admin/article', [...])
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Article->index()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Article))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-01-24 02:29:03 --> cURL error 6: Could not resolve host: api-ap1.pusher.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api-ap1.pusher.com/apps/1541690/events?auth_key=81fed0e008d5c25a0657&auth_timestamp=1674548943&auth_version=1.0&body_md5=edc6657a206fd78964d50cf2232316a3&auth_signature=27de87a241a6edf75add0e2c3cab38d9b9fbbd4de603a0fe857ef6fb23a61bf3
in VENDORPATH\pusher\pusher-php-server\src\Pusher.php on line 782.
 1 VENDORPATH\pusher\pusher-php-server\src\Pusher.php(440): Pusher\Pusher->post('/apps/1541690/events', '{"name":"my-event","data":"{\\"message\\":\\"Ada Artikel Yang Harus di Verifikasi\\"}","channel":"my-channel"}')
 2 APPPATH\Controllers\Article.php(91): Pusher\Pusher->trigger('my-channel', 'my-event', [...])
 3 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Article->save()
 4 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Article))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-01-24 03:30:39 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('127.0.0.1', 'root', '', 'db_event', 3306, '', 0)
#1 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2295): CodeIgniter\Database\BaseConnection->query('INSERT INTO `vi...', Array, false)
#4 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Model.php(329): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Model.php(729): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\BaseModel.php(692): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\web_event-main\app\Controllers\Home.php(17): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Home->index()
#10 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\web_event-main\public\index.php(55): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2295): CodeIgniter\Database\BaseConnection->query('INSERT INTO `vi...', Array, false)
#3 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Model.php(329): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Model.php(729): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\BaseModel.php(692): CodeIgniter\Model->insert(Array, false)
#7 C:\xampp\htdocs\web_event-main\app\Controllers\Home.php(17): CodeIgniter\BaseModel->save(Array)
#8 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Home->index()
#9 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\web_event-main\public\index.php(55): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2023-01-24 03:30:39 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2295): CodeIgniter\Database\BaseConnection->query('INSERT INTO `visitors` (`type`, `id_articles`) VALUES (:type:, :id_articles:)', [...], false)
 3 SYSTEMPATH\Model.php(329): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(729): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(692): CodeIgniter\Model->insert([...], false)
 7 APPPATH\Controllers\Home.php(17): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 9 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
10 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-01-24 03:31:57 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('127.0.0.1', 'root', '', 'db_event', 3306, '', 0)
#1 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2295): CodeIgniter\Database\BaseConnection->query('INSERT INTO `vi...', Array, false)
#4 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Model.php(329): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Model.php(729): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\BaseModel.php(692): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\web_event-main\app\Controllers\Home.php(17): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Home->index()
#10 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\web_event-main\public\index.php(55): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2295): CodeIgniter\Database\BaseConnection->query('INSERT INTO `vi...', Array, false)
#3 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Model.php(329): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Model.php(729): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\BaseModel.php(692): CodeIgniter\Model->insert(Array, false)
#7 C:\xampp\htdocs\web_event-main\app\Controllers\Home.php(17): CodeIgniter\BaseModel->save(Array)
#8 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Home->index()
#9 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\web_event-main\public\index.php(55): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2023-01-24 03:31:57 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2295): CodeIgniter\Database\BaseConnection->query('INSERT INTO `visitors` (`type`, `id_articles`) VALUES (:type:, :id_articles:)', [...], false)
 3 SYSTEMPATH\Model.php(329): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(729): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(692): CodeIgniter\Model->insert([...], false)
 7 APPPATH\Controllers\Home.php(17): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 9 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
10 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-01-24 03:58:50 --> mysqli_sql_exception: Unknown column 'a' in 'order clause' in C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Model.php(240): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\web_event-main\app\Controllers\Home.php(47): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Home->article()
#8 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\web_event-main\public\index.php(55): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2023-01-24 03:58:50 --> Unknown column 'a' in 'order clause'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `articles`
JOIN `categories` ON `categories`.`id_categories` = `articles`.`id_categories`
WHERE `status` = :status:
ORDER BY `a` DESC', [...], false)
 2 SYSTEMPATH\Model.php(240): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\Home.php(47): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->article()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-01-24 04:03:18 --> Undefined index: name
in APPPATH\Views\article-detail.php on line 92.
 1 APPPATH\Views\article-detail.php(92): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index: name', 'APPPATH\\Views\\article-detail.php', 92, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\article-detail.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1177): CodeIgniter\View\View->render('article-detail', [], true)
 5 APPPATH\Controllers\Home.php(83): view('article-detail', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->detail('sdfsdf')
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-01-24 04:04:31 --> Undefined variable: user
in APPPATH\Views\article-detail.php on line 92.
 1 APPPATH\Views\article-detail.php(92): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: user', 'APPPATH\\Views\\article-detail.php', 92, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\article-detail.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1177): CodeIgniter\View\View->render('article-detail', [], true)
 5 APPPATH\Controllers\Home.php(83): view('article-detail', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->detail('sdfsdf')
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-01-24 04:07:45 --> Array to string conversion
in APPPATH\Controllers\Home.php on line 83.
 1 APPPATH\Controllers\Home.php(83): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Array to string conversion', 'APPPATH\\Controllers\\Home.php', 83, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->detail('sdfsdf')
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-01-24 04:07:53 --> Array to string conversion
in APPPATH\Controllers\Home.php on line 83.
 1 APPPATH\Controllers\Home.php(83): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Array to string conversion', 'APPPATH\\Controllers\\Home.php', 83, [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->detail('sdfsdf')
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-01-24 04:10:28 --> mysqli_sql_exception: Column 'slug' in where clause is ambiguous in C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\web_event-main\app\Controllers\Home.php(74): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Home->detail('sdfsdf')
#8 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\web_event-main\public\index.php(55): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2023-01-24 04:10:28 --> Column 'slug' in where clause is ambiguous
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `articles`
JOIN `users` ON `users`.`id_users` = `articles`.`id_users`
JOIN `community` ON `community`.`id_community` = `articles`.`id_community`
WHERE `slug` = :slug:
 LIMIT 1', [...], false)
 2 SYSTEMPATH\Model.php(267): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 4 APPPATH\Controllers\Home.php(74): CodeIgniter\BaseModel->first()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->detail('sdfsdf')
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-01-24 04:12:27 --> mysqli_sql_exception: Column 'slug' in where clause is ambiguous in C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\web_event-main\app\Controllers\Home.php(73): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Home->detail('sdfsdf')
#8 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\web_event-main\public\index.php(55): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2023-01-24 04:12:27 --> Column 'slug' in where clause is ambiguous
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `articles`
JOIN `users` ON `users`.`id_users` = `articles`.`id_users`
JOIN `categories` ON `categories`.`id_categories` = `articles`.`id_categories`
JOIN `community` ON `community`.`id_community` = `articles`.`id_community`
WHERE `slug` = :slug:
 LIMIT 1', [...], false)
 2 SYSTEMPATH\Model.php(267): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 4 APPPATH\Controllers\Home.php(73): CodeIgniter\BaseModel->first()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->detail('sdfsdf')
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-01-24 04:12:44 --> mysqli_sql_exception: Unknown column 'articles.id_community' in 'on clause' in C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\web_event-main\app\Controllers\Home.php(73): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Home->detail('sdfsdf')
#8 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\web_event-main\public\index.php(55): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2023-01-24 04:12:44 --> Unknown column 'articles.id_community' in 'on clause'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `articles`
JOIN `users` ON `users`.`id_users` = `articles`.`id_users`
JOIN `categories` ON `categories`.`id_categories` = `articles`.`id_categories`
JOIN `community` ON `community`.`id_community` = `articles`.`id_community`
WHERE `articles`.`slug` = :articles.slug:
 LIMIT 1', [...], false)
 2 SYSTEMPATH\Model.php(267): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 4 APPPATH\Controllers\Home.php(73): CodeIgniter\BaseModel->first()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->detail('sdfsdf')
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-01-24 04:13:13 --> mysqli_sql_exception: Column 'slug' in where clause is ambiguous in C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\web_event-main\app\Controllers\Home.php(74): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Home->detail('sdfsdf')
#8 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\web_event-main\public\index.php(55): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2023-01-24 04:13:13 --> Column 'slug' in where clause is ambiguous
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `articles`
JOIN `users` ON `users`.`id_users` = `articles`.`id_users`
JOIN `community` ON `community`.`id_community` = `articles`.`id_community`
WHERE `slug` = :slug:
 LIMIT 1', [...], false)
 2 SYSTEMPATH\Model.php(267): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 4 APPPATH\Controllers\Home.php(74): CodeIgniter\BaseModel->first()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->detail('sdfsdf')
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-01-24 04:13:25 --> mysqli_sql_exception: Unknown column 'articles.id_community' in 'on clause' in C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\web_event-main\app\Controllers\Home.php(74): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Home->detail('sdfsdf')
#8 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\web_event-main\public\index.php(55): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2023-01-24 04:13:25 --> Unknown column 'articles.id_community' in 'on clause'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `articles`
JOIN `users` ON `users`.`id_users` = `articles`.`id_users`
JOIN `community` ON `community`.`id_community` = `articles`.`id_community`
WHERE `articles`.`slug` = :articles.slug:
 LIMIT 1', [...], false)
 2 SYSTEMPATH\Model.php(267): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 4 APPPATH\Controllers\Home.php(74): CodeIgniter\BaseModel->first()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->detail('sdfsdf')
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-01-24 04:13:26 --> mysqli_sql_exception: Unknown column 'articles.id_community' in 'on clause' in C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\web_event-main\app\Controllers\Home.php(74): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Home->detail('sdfsdf')
#8 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\web_event-main\public\index.php(55): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\web_event-main\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2023-01-24 04:13:26 --> Unknown column 'articles.id_community' in 'on clause'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `articles`
JOIN `users` ON `users`.`id_users` = `articles`.`id_users`
JOIN `community` ON `community`.`id_community` = `articles`.`id_community`
WHERE `articles`.`slug` = :articles.slug:
 LIMIT 1', [...], false)
 2 SYSTEMPATH\Model.php(267): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 4 APPPATH\Controllers\Home.php(74): CodeIgniter\BaseModel->first()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->detail('sdfsdf')
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-01-24 04:15:40 --> Undefined index: categories.name
in APPPATH\Views\article-detail.php on line 97.
 1 APPPATH\Views\article-detail.php(97): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index: categories.name', 'APPPATH\\Views\\article-detail.php', 97, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\article-detail.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1177): CodeIgniter\View\View->render('article-detail', [], true)
 5 APPPATH\Controllers\Home.php(84): view('article-detail', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->detail('sdfsdf')
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-01-24 04:23:01 --> Undefined variable: user
in APPPATH\Views\admin\users.php on line 91.
 1 APPPATH\Views\admin\users.php(91): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: user', 'APPPATH\\Views\\admin\\users.php', 91, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\admin\\users.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1177): CodeIgniter\View\View->render('admin/users', [], true)
 5 APPPATH\Controllers\Users.php(23): view('admin/users', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Users->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-01-24 04:24:16 --> Undefined variable: user
in APPPATH\Views\admin\users.php on line 91.
 1 APPPATH\Views\admin\users.php(91): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: user', 'APPPATH\\Views\\admin\\users.php', 91, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\admin\\users.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1177): CodeIgniter\View\View->render('admin/users', [], true)
 5 APPPATH\Controllers\Users.php(23): view('admin/users', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Users->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-01-24 04:24:17 --> Undefined variable: user
in APPPATH\Views\admin\users.php on line 91.
 1 APPPATH\Views\admin\users.php(91): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: user', 'APPPATH\\Views\\admin\\users.php', 91, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\admin\\users.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1177): CodeIgniter\View\View->render('admin/users', [], true)
 5 APPPATH\Controllers\Users.php(23): view('admin/users', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Users->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-01-24 04:24:18 --> Undefined variable: user
in APPPATH\Views\admin\users.php on line 91.
 1 APPPATH\Views\admin\users.php(91): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: user', 'APPPATH\\Views\\admin\\users.php', 91, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\admin\\users.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1177): CodeIgniter\View\View->render('admin/users', [], true)
 5 APPPATH\Controllers\Users.php(23): view('admin/users', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Users->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-01-24 04:24:18 --> Undefined variable: user
in APPPATH\Views\admin\users.php on line 91.
 1 APPPATH\Views\admin\users.php(91): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: user', 'APPPATH\\Views\\admin\\users.php', 91, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\admin\\users.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1177): CodeIgniter\View\View->render('admin/users', [], true)
 5 APPPATH\Controllers\Users.php(23): view('admin/users', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Users->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-01-24 04:24:19 --> Undefined variable: user
in APPPATH\Views\admin\users.php on line 91.
 1 APPPATH\Views\admin\users.php(91): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: user', 'APPPATH\\Views\\admin\\users.php', 91, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\admin\\users.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1177): CodeIgniter\View\View->render('admin/users', [], true)
 5 APPPATH\Controllers\Users.php(23): view('admin/users', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Users->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-01-24 04:26:56 --> Undefined index: users.name
in APPPATH\Views\admin\users.php on line 250.
 1 APPPATH\Views\admin\users.php(250): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index: users.name', 'APPPATH\\Views\\admin\\users.php', 250, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\admin\\users.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1177): CodeIgniter\View\View->render('admin/users', [], true)
 5 APPPATH\Controllers\Users.php(23): view('admin/users', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Users->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-01-24 21:53:16 --> cURL error 6: Could not resolve host: api-ap1.pusher.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api-ap1.pusher.com/apps/1541690/events?auth_key=81fed0e008d5c25a0657&auth_timestamp=1674618796&auth_version=1.0&body_md5=edc6657a206fd78964d50cf2232316a3&auth_signature=9dddcfe049271ecf716dd8f6f31d2486948cea5be2350a840defe908ef023549
in VENDORPATH\pusher\pusher-php-server\src\Pusher.php on line 782.
 1 VENDORPATH\pusher\pusher-php-server\src\Pusher.php(440): Pusher\Pusher->post('/apps/1541690/events', '{"name":"my-event","data":"{\\"message\\":\\"Ada Artikel Yang Harus di Verifikasi\\"}","channel":"my-channel"}')
 2 APPPATH\Controllers\Article.php(91): Pusher\Pusher->trigger('my-channel', 'my-event', [...])
 3 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Article->save()
 4 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Article))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-01-24 22:00:23 --> Trying to access array offset on value of type null
in APPPATH\Views\home.php on line 98.
 1 APPPATH\Views\home.php(98): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to access array offset on value of type null', 'APPPATH\\Views\\home.php', 98, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\home.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1177): CodeIgniter\View\View->render('home', [], true)
 5 APPPATH\Controllers\Home.php(38): view('home', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
